''' knowledge about the SSAGA and the core phenotype file '''

ssaga_cols = [
    'AL1',
    'AL1AgeOns',
    'AL4a',
    'AL4e1',
    'AL4e2',
    'AL4e3',
    'AL4fx',
    'AL4f1',
    'AL4f2',
    'AL4f3',
    'AL5',
    'AL6',
    'AL6a',
    'AL8',
    'AL8a',
    'AL8AgeOns',
    'AL8d',
    'AL9',
    'AL9bAgeOns',
    'AL9bAgeRec',
    'AL16b',
    'AL16AgeOns',
    'AL17b',
    'AL17AgeOns',
    'AL17AgeRec',
    'AL19',
    'AL22AgeOns',
    'AL22AgeRec',
    'AL25AgeOns',
    'AL25AgeRec',
    'AL31AgeOns',
    'AL33AgeOns',
    'AL33AgeRec',
    'AL34AgeOns',
    'AL35AgeOns',
    'AL37aAgeOns',
    'AL37aAgeRec',
    'AL37eAgeOns',
    'AL37eAgeRec',
    'AL43A',
    'AL45bAgeOns',
    'AL45bAgeRec', ]

ssaga_drink_AL3_cols = ['AL3WEEK_BEER1',
                        'AL3WEEK_BEER2',
                        'AL3WEEK_BEER3',
                        'AL3WEEK_BEER4',
                        'AL3WEEK_BEER5',
                        'AL3WEEK_BEER6',
                        'AL3WEEK_BEER7',
                        'AL3WEEK_LIQUOR1',
                        'AL3WEEK_LIQUOR2',
                        'AL3WEEK_LIQUOR3',
                        'AL3WEEK_LIQUOR4',
                        'AL3WEEK_LIQUOR5',
                        'AL3WEEK_LIQUOR6',
                        'AL3WEEK_LIQUOR7',
                        'AL3WEEK_OTHER1',
                        'AL3WEEK_OTHER2',
                        'AL3WEEK_OTHER3',
                        'AL3WEEK_OTHER4',
                        'AL3WEEK_OTHER5',
                        'AL3WEEK_OTHER6',
                        'AL3WEEK_OTHER7',
                        'AL3WEEK_WINE1',
                        'AL3WEEK_WINE2',
                        'AL3WEEK_WINE3',
                        'AL3WEEK_WINE4',
                        'AL3WEEK_WINE5',
                        'AL3WEEK_WINE6',
                        'AL3WEEK_WINE7', ]

ssaga_drink_AL4_cols = ['AL4WEEK_BEER1',
                        'AL4WEEK_BEER2',
                        'AL4WEEK_BEER3',
                        'AL4WEEK_BEER4',
                        'AL4WEEK_BEER5',
                        'AL4WEEK_BEER6',
                        'AL4WEEK_BEER7',
                        'AL4WEEK_LIQUOR1',
                        'AL4WEEK_LIQUOR2',
                        'AL4WEEK_LIQUOR3',
                        'AL4WEEK_LIQUOR4',
                        'AL4WEEK_LIQUOR5',
                        'AL4WEEK_LIQUOR6',
                        'AL4WEEK_LIQUOR7',
                        'AL4WEEK_OTHER1',
                        'AL4WEEK_OTHER2',
                        'AL4WEEK_OTHER3',
                        'AL4WEEK_OTHER4',
                        'AL4WEEK_OTHER5',
                        'AL4WEEK_OTHER6',
                        'AL4WEEK_OTHER7',
                        'AL4WEEK_WINE1',
                        'AL4WEEK_WINE2',
                        'AL4WEEK_WINE3',
                        'AL4WEEK_WINE4',
                        'AL4WEEK_WINE5',
                        'AL4WEEK_WINE6',
                        'AL4WEEK_WINE7', ]

dx_ssaga_cols = ['ALD4DPSX',
                 'ALD4DPDX',
                 'ALD4DPAO',
                 'ALD4ABDX',
                 'ALD4ABSX',
                 'ALD4D1',
                 'ALD4D2',
                 'ALD4D3',
                 'ALD4D4',
                 'ALD4D5',
                 'ALD4D6',
                 'ALD4D7',
                 'ALD4ABA1',
                 'ALD4ABA2',
                 'ALD4ABA3',
                 'ALD4ABA4',
                 'TBD4DPSX',
                 'TBD4DPDX',
                 'TBD4DPAO',
                 'MJD4DPSX',
                 'MJD4DPDX',
                 'MJD4DPAO',
                 'MJD4ABDX',
                 'MJD4ABSX',
                 'COD4DPDX',
                 'COD4DPSX',
                 'COD4DPAO',
                 'COD4ABDX',
                 'COD4ABSX',
                 'STD4DPDX',
                 'STD4DPSX',
                 'STD4DPAO',
                 'STD4ABDX',
                 'STD4ABSX',
                 'SDD4DPDX',
                 'SDD4DPSX',
                 'SDD4DPAO',
                 'SDD4ABDX',
                 'SDD4ABSX',
                 'OPD4DPDX',
                 'OPD4DPSX',
                 'OPD4DPAO',
                 'OPD4ABDX',
                 'OPD4ABSX',
                 'OTHERDRUGD4DPDX',
                 'OTHERDRUGD4DPSX',
                 'OTHERDRUGD4DPAO',
                 'OTHERDRUGD4ABDX',
                 'OTHERDRUGD4ABSX',
                 'DPD4DX',
                 'DPD4SX',
                 'ASD4DX',
                 'ASD4A',
                 'ASD4C',
                 'ASD4ASX_CLEAN',
                 'ASD4ASX_CLEANORDIRTY',
                 'ASD4CSX_CLEAN',
                 'ASD4CSX_CLEANORDIRTY',
                 'ADD4DX',
                 'ADD4A1SX',
                 'ADD4A2HYPSX',
                 'ADD4A2IMPSX',
                 'ADD4A2SX',
                 'ODD4DX',
                 'ODD4SX',
                 'ODD4BCOUNT',
                 'PTD4DX',
                 'PTD4CRITBSX',
                 'PTD4CRITCSX',
                 'PTD4CRITDSX',
                 'OCOBD4DX',
                 'OCCPD4DX',
                 'SPD4DX',
                 'PND4DX',
                 'PND4NUMSX',
                 'AGD4DX', ]

dx_ssaga_ald_cols = ['ALD4DPSX',
                 'ALD4DPDX',
                 'ALD4DPAO',
                 'ALD4ABDX',
                 'ALD4ABSX',
                 'ALD4D1',
                 'ALD4D2',
                 'ALD4D3',
                 'ALD4D4',
                 'ALD4D5',
                 'ALD4D6',
                 'ALD4D7',
                 'ALD4ABA1',
                 'ALD4ABA2',
                 'ALD4ABA3',
                 'ALD4ABA4',]

dx_ssaga_mj_cols = ['MJD4DPSX', 
                    'MJD4DPDX', 
                    'MJD4DPAO', 
                    'MJD4ABDX', 
                    'MJD4ABSX', 
                    'MJD4D1', 
                    'MJD4D2', ]

ssa_mj_cols = ['MJ1', 
                'MJ1a', 
                'MJ2AgeOns', 
                'MJ2C', 
                'MJ2d', 
                'MJ3_num', 
                'MJ3_unit', 
                'MJ3c_NUM', 
                'MJ3c_UNIT', 
                'MJ3d', 
                'MJ3e', 
                'MJ4', ]
